### PR TITLE
Fixes Azure DevOps path

### PR DESCRIPTION
**Pull request by cdambo**

### CODE REVIEW

**Comment by ben-gibson** [comment]
Nice, if you bump the plugin version to `4.0.6` [here ](https://github.com/ben-gibson/GitLink/blob/master/gradle.properties#L7) and add an item to the [CHANGELOG.md](https://github.com/ben-gibson/GitLink/blob/master/CHANGELOG.md) under the `UNRELEASED` heading (you don't need to change the heading itself). I'll release it.

**Comment by cdambo** [comment]
> Nice, if you bump the plugin version to `4.0.6` [here ](https://github.com/ben-gibson/GitLink/blob/master/gradle.properties#L7) and add an item to the [CHANGELOG.md](https://github.com/ben-gibson/GitLink/blob/master/CHANGELOG.md) under the `UNRELEASED` heading (you don't need to change the heading itself). I'll release it.

Done

**Review by ben-gibson — APPROVED** [review]

**Comment by ben-gibson** [comment]
Thanks!

**Comment by cdambo** [comment]
> Thanks!

Thank you for this great plugin!

**Pull request merged**
