### PR TITLE
refactor: get rid of  ServiceManager.getService() deprecation

### PR DESCRIPTION
**Pull request by pahan35**
- [x] Resolve  ServiceManager.getService() deprecations.
- [x] Allow publishing for 2021.3 EAP.

### CODE REVIEW

**Comment by pahan35** [comment]
@ben-gibson could you please publish these changes?

I'm kind of tired of exceptions and broken preferences in 2021.3 EAP. I use the 3.3.3 version. It works well but throws an exception when opening preferences.

**Comment by pahan35** [comment]
@ben-gibson any chance that you can check it?

We need it, because we can't configure plugin in 2021.3EAP without it.
image

**Comment by ben-gibson** [comment]
👀 , thanks for this! My notification preferences must be wrong as I didn't receive any notification for this!

**Comment by ben-gibson** [comment]
I'll merge and release this tonight!

**Comment by ben-gibson** [comment]
Released as `3.3.6`. Thanks for this!

**Pull request merged**
